apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-world-deploy
  labels:
    app: hello-world

spec:

  replicas: 5

  selector:
    matchLabels:
      app: hello-world

  template:

    metadata:
      name: minikube-intro-workshop
      labels:
        name: workshop-web
        app: hello-world

    spec:

      containers:
      - name: web
        image: acinwinstack/hello_world:minikube-intro-workshop
        imagePullPolicy: IfNotPresent
        env:
          - name: REDIS_HOST
            value: "172.17.0.4" #replace with acutal redis ip
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol
          mountPath: /home/redis

      volumes:
      - name: vol
        hostPath:
          path: /webvol

