apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
 containers:
 - name: web
   image: acinwinstack/hello_world:minikube-intro-workshop
   imagePullPolicy: IfNotPresent
   env:
   - name: REDIS_HOST
     value: "172.17.0.4" #replace with acutal redis ip
   ports:
   - containerPort: 80
